/*
 * This Spock specification was auto generated by running 'gradle init --type groovy-library'
 * by 'kallin' at '24/01/15 7:33 PM' with Gradle 2.1
 *
 * @author kallin, @date 24/01/15 7:33 PM
 */

import spock.lang.Specification

class LibraryTest extends Specification{
    def "someLibraryMethod returns true"() {
        setup:
        Library lib = new Library()
        when:
        def result = lib.someLibraryMethod()
        then:
        result == true
    }
}
