/*
 * This Groovy source file was auto generated by running 'gradle buildInit --type groovy-library'
 * by 'kallin' at '24/01/15 7:33 PM' with Gradle 2.1
 *
 * @author kallin, @date 24/01/15 7:33 PM
 */
class Library {
    boolean someLibraryMethod() {
        true
    }
}
